# Generated by Django 4.1.1 on 2022-09-20 18:31

import coderockr.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "started_date",
                    models.DateField(
                        validators=[coderockr.core.validators.validate_started_date],
                        verbose_name="iniciado em",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("withdraw", "Retirado"),
                            ("not_settled", "Não Liquidado"),
                        ],
                        default="not_settled",
                        max_length=11,
                        verbose_name="status",
                    ),
                ),
                (
                    "initial_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="valor inicial",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="balanço",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="taxa",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor recebíveis",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dono do investimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investimento",
                "verbose_name_plural": "Investimentos",
            },
        ),
        migrations.CreateModel(
            name="Gain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "investment_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="valor do investimento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="valor do ganho"
                    ),
                ),
                ("period", models.DateField(verbose_name="período referente")),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.investment",
                        verbose_name="investimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ganho",
                "verbose_name_plural": "Ganhos",
            },
        ),
    ]
