# Generated by Django 4.1.1 on 2022-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="nome"
            ),
        ),
    ]
